Repository aroyofficial/FlexiForm.Database, pull requests merged in 2025-06, with the labels that each got.

#10 Fix basepath for mirgation scripts #9
  tools/Create-Migration.ps1
Labels: bug

#12 Support alter scripts #11
  FlexiForm.Database/Enumerations/ExecutionTarget.cs
  FlexiForm.Database/Enumerations/ScriptType.cs
  FlexiForm.Database/Extensions/ScriptInspector.cs
  FlexiForm.Database/Scripts/Alters/Down/20250621122508435_alter_tblusers.sql
  FlexiForm.Database/Scripts/Alters/Down/20250621123933719_alter_tblforms.sql
  FlexiForm.Database/Scripts/Alters/Down/20250621131928011_alter_tblformfields.sql
  FlexiForm.Database/Scripts/Alters/Down/20250621135722549_alter_tblformfieldmappings.sql
  FlexiForm.Database/Scripts/Alters/Down/20250621141544781_alter_tblsubmissions.sql
  FlexiForm.Database/Scripts/Alters/Down/20250621143606196_alter_tblsubmissionentries.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621122508435_alert_tblusers.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621123933719_alert_tblforms.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621131928011_alert_tblformfields.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621135722549_alert_tblformfieldmappings.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621141544781_alert_tblsubmissions.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621143606196_alert_tblsubmissionentries.sql
  FlexiForm.Database/Services/TaskRunner.cs
  tools/Create-Migration.ps1
Labels: feature

#15 Add task level profiler #14
  FlexiForm.Database/Configurations/TaskRunnerConfiguration.cs
  FlexiForm.Database/Enumerations/MigrationTaskStatus.cs
  FlexiForm.Database/Events/PerformanceTrackingEventArgs.cs
  FlexiForm.Database/Events/TaskLogSummaryEventArgs.cs
  FlexiForm.Database/FlexiForm.Database.csproj
  FlexiForm.Database/Logging/Logger.cs
  FlexiForm.Database/Models/ExecutionProfile.cs
  FlexiForm.Database/Models/MigrationTask.cs
  FlexiForm.Database/Models/TaskLog.cs
  FlexiForm.Database/Program.cs
  FlexiForm.Database/Services/TaskExecutor.cs
  FlexiForm.Database/Services/TaskLogger.cs
  FlexiForm.Database/Services/TaskProfiler.cs
  FlexiForm.Database/Services/TaskRunner.cs
Labels: enhancement

#19 Add migration tracking tables #17
  FlexiForm.Database/Configurations/MigrationEngineConfiguration.cs
  FlexiForm.Database/Configurations/TaskRunnerConfiguration.cs
  FlexiForm.Database/Enumerations/ErrorCode.cs
  FlexiForm.Database/Enumerations/MigrationRunMode.cs
  FlexiForm.Database/Enumerations/MigrationStrategy.cs
  FlexiForm.Database/Enumerations/TaskRunnerMode.cs
  FlexiForm.Database/Events/OnCompletedEventArgs.cs
  FlexiForm.Database/Events/OnStartEventArgs.cs
  FlexiForm.Database/Events/PerformanceTrackingEventArgs.cs
  FlexiForm.Database/Events/TaskLogSummaryEventArgs.cs
  FlexiForm.Database/Exceptions/MigrationInfrastructureException.cs
  FlexiForm.Database/Extensions/ScriptInspector.cs
  FlexiForm.Database/Models/DBCommand.cs
  FlexiForm.Database/Models/Migration.cs
  FlexiForm.Database/Models/MigrationLog.cs
  FlexiForm.Database/Models/MigrationTask.cs
  FlexiForm.Database/Models/Script.cs
  FlexiForm.Database/Models/ScriptMetadata.cs
  FlexiForm.Database/Models/TaskLog.cs
  FlexiForm.Database/Program.cs
  FlexiForm.Database/Scripts/Alters/Down/20250621135722549_alter_tblformfieldmappings.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621122508435_alert_tblusers.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621122508435_alter_tblusers.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621123933719_alert_tblforms.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621123933719_alter_tblforms.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621131928011_alert_tblformfields.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621131928011_alter_tblformfields.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621135722549_alert_tblformfieldmappings.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621135722549_alter_tblformfieldmappings.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621141544781_alert_tblsubmissions.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621141544781_alter_tblsubmissions.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621143606196_alert_tblsubmissionentries.sql
  FlexiForm.Database/Scripts/Alters/Up/20250621143606196_alter_tblsubmissionentries.sql
  FlexiForm.Database/Scripts/Infrastructure/schema_tblmigrationhistory.sql
  FlexiForm.Database/Scripts/Infrastructure/usp_addmigrationhistory.sql
  FlexiForm.Database/Scripts/Infrastructure/usp_clearmigrationhistory.sql
  FlexiForm.Database/Scripts/Infrastructure/usp_getmigrationhistory.sql
  FlexiForm.Database/Scripts/Schemas/Up/20250621122019847_schema_tblusers.sql
  FlexiForm.Database/Scripts/Schemas/Up/20250621123807292_schema_tblforms.sql
  FlexiForm.Database/Scripts/Schemas/Up/20250621125537401_schema_tblformfields.sql
  FlexiForm.Database/Scripts/Schemas/Up/20250621135318333_schema_tblformfieldmappings.sql
  FlexiForm.Database/Scripts/Schemas/Up/20250621141228736_schema_tblsubmissions.sql
  FlexiForm.Database/Scripts/Schemas/Up/20250621143537125_schema_tblsubmissionentries.sql
  FlexiForm.Database/Scripts/StoredProcedures/Up/20250621144910071_proc_uspcreateuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Up/20250621150003273_proc_uspgetuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Up/20250621151252057_proc_uspupdateuser.sql
  FlexiForm.Database/Services/DBConnector.cs
  FlexiForm.Database/Services/GlobalProfiler.cs
  FlexiForm.Database/Services/Logger.cs
  FlexiForm.Database/Services/MigrationEngine.cs
  FlexiForm.Database/Services/MigrationProfiler.cs
  FlexiForm.Database/Services/TaskExecutor.cs
  FlexiForm.Database/Services/TaskLogger.cs
  FlexiForm.Database/Services/TaskProfiler.cs
  FlexiForm.Database/Services/TaskRunner.cs
  tools/Run-Migration.ps1
Labels: enhancement

#20 Add Void column #3
  FlexiForm.Database/Scripts/Alters/Down/20250628104248132_alter_tblusers.sql
  FlexiForm.Database/Scripts/Alters/Up/20250628104248132_alter_tblusers.sql
  FlexiForm.Database/Scripts/StoredProcedures/Down/20250629090545753_proc_usp_deleteuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Down/20250629102248824_proc_usp_getuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Down/20250629102950154_proc_usp_updateuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Up/20250629090545753_proc_usp_deleteuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Up/20250629102248824_proc_usp_getuser.sql
  FlexiForm.Database/Scripts/StoredProcedures/Up/20250629102950154_proc_usp_updateuser.sql
Labels: feature
